### ISSUE TITLE
Crash when starting Spice86.View

### ISSUE THREAD

**Issue by uxmal** [OpenRakis/Spice86#1]
When starting the GUI, the follow exception occurs:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=The resource /Assets/Spice86.ico could not be found.
  Source=Avalonia.DesktopRuntime
  StackTrace:
   at Avalonia.Shared.PlatformSupport.AssetLoader.OpenAndGetAssembly(Uri uri, Uri baseUri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 96
   at Avalonia.Shared.PlatformSupport.AssetLoader.Open(Uri uri, Uri baseUri) in /_/src/Shared/PlatformSupport/AssetLoader.cs:line 71
   at Avalonia.Markup.Xaml.Converters.IconTypeConverter.CreateIconFromPath(ITypeDescriptorContext context, String s) in /_/src/Markup/Avalonia.Markup.Xaml/Converters/IconTypeConverter.cs:line 43
   at Avalonia.Markup.Xaml.Converters.IconTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value) in /_/src/Markup/Avalonia.Markup.Xaml/Converters/IconTypeConverter.cs:line 32
   at Spice86.View.Views.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in d:\dev\uxmal\emu\Spice86\src\Spice86.View\Views/MainWindow.axaml:line 8
   at Spice86.View.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at Spice86.View.Views.MainWindow.InitializeComponent() in d:\dev\uxmal\emu\Spice86\src\Spice86.View\Views\MainWindow.axaml.cs:line 19
   at Spice86.View.Views.MainWindow..ctor() in d:\dev\uxmal\emu\Spice86\src\Spice86.View\Views\MainWindow.axaml.cs:line 11
   at Spice86.View.App.OnFrameworkInitializationCompleted() in d:\dev\uxmal\emu\Spice86\src\Spice86.View\App.axaml.cs:line 47
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 313
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 187
   at Spice86.View.Program.Main(String[] args) in d:\dev\uxmal\emu\Spice86\src\Spice86.View\Program.cs:line 21
```
It appears the icon `Assets\Spice86.ico` is missing. There does exist `Assets\Ix86.ico`, however. Changing the path to the icon in `MainWindow.axaml` fixes the problem.

**Comment by maximilien-noal** [comment]
Hello,
Thank you for your interest ! :) 
That's normal, It is in a very early / mid  stage of translation. For the moment, the UI needs a lot of work.

**Comment by maximilien-noal** [comment]
Fixed
