### ISSUE TITLE
VGA Renderer: IndexOutOfRangeException with some programs in DrawTextMode (tested with Hero Quest's intro)

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#332]
**Describe the bug**

Some programs, such as Cadaver's INTRO.EXE and Hero Quest's INTRO.EXE make Renderer.cs throw an IndexOutOfRangeException:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Spice86.Core.Emulator.Devices.Video.Renderer.DrawTextMode(Span`1 frameBuffer, Int32& destinationAddress, Byte plane0, Byte plane1, Int32 scanline) in /home/max/repos/Spice86/src/Spice86.Core/Emulator/Devices/Video/Renderer.cs:line 249
   at Spice86.Core.Emulator.Devices.Video.Renderer.Render(Span`1 frameBuffer) in /home/max/repos/Spice86/src/Spice86.Core/Emulator/Devices/Video/Renderer.cs:line 136
   at Spice86.Core.Emulator.Devices.Video.VgaCard.Render(Span`1 buffer) in /home/max/repos/Spice86/src/Spice86.Core/Emulator/Devices/Video/VgaCard.cs:line 48
   at Spice86.ViewModels.VideoBufferViewModel.<Draw>b__31_0() in /home/max/repos/Spice86/src/Spice86/ViewModels/VideoBufferViewModel.cs:line 161
   at Spice86.ViewModels.VideoBufferViewModel.DrawThreadMethod() in /home/max/repos/Spice86/src/Spice86/ViewModels/VideoBufferViewModel.cs:line 54

```

This happens at the beginning of the intro.

The code line number 249 ("frameBuffer[destinationAddress++] = pixel;") triggers the error:

```
[...]
        // The 8 pixels to render this line come from the font which is stored in plane 2.
        byte fontByte = _memory.Planes[2, fontAddress + scanline];
        for (int x = 0; x < _state.SequencerRegisters.ClockingModeRegister.DotsPerClock; x++) {
            uint pixel = (fontByte & 0x80 >> x) != 0 ? foreGroundColor : backGroundColor;
            frameBuffer[destinationAddress++] = pixel;
        }
[...]
```

```
backGroundColor = {uint} 4278190250 0xFF0000AA
destinationAddress = {int} 256001 0x3E801
fontAddress = {int} 576 0x240
fontByte = {byte} 24 0x18
foreGroundColor = {uint} 4278233600 0xFF00AA00
frameBuffer = {Span<uint>} System.Span<UInt32>[256000]
index = {int} 2 0x2
pixel = {uint} 4278190250 0xFF0000AA
plane0 = {byte} 18 0x12
plane1 = {byte} 18 0x12
scanline = {int} 7 0x7
x = {int} 7 0x7
```

**To Reproduce**

1. Run Spice with the following command line arguments:

```
-d false --Ems -s
```

2. Program -> Start Program... -> Select INTRO.EXE
3. Wait for the error.

**Expected behavior**

The Hero Quest INTRO should run.

**Screenshots**

![image](https://github.com/OpenRakis/Spice86/assets/1087524/c4993767-ec5b-4d18-baa5-b50d76429a4e)

 - OS: Fedora Workstation
 - Version: master branch commit 9c9a137

**Additional context**

**Comment by JorisVanEijden** [comment]
I have not been able to reproduce this, but it sounds like the same is as with Duke2: the screen resolution is changing in the middle of a frame. Proposed solution is the same. Catch and ignore the `IndexOutOfRangeException`, to skip the frame.

**Comment by maximilien-noal** [comment]
Fixed via PR. https://github.com/OpenRakis/Spice86/pull/336
