### ISSUE TITLE
Dune CD failure

### ISSUE THREAD

**Issue by akaWolf** [OpenRakis/Spice86#94]
I've tried to run Dune like so:
Spice86 -e DUNE.EXE

And got:
```[23:18:03 DBG {SourceContext="Spice86.Emulator.CPU.Cpu"}] Before execution: 0xFE Cycles=8077 CS:IP=0xF000:0x20/0xF0020 EAX=0x4B00 EBX=0x0 ECX=0x6 EDX=0x1A ESI=0x706 EDI=0x54 EBP=0x22B ESP=0x172 SS=0x1000 DS=0x1000 ES=0x1000 FS=0x0 GS=0x0 flags=0x2 (         ) 
[23:18:03 DBG {SourceContext="Spice86.Emulator.CPU.Cpu"}] callback 0x21
[23:18:03 ERR {SourceContext="Spice86.UI.ViewModels.MainWindowViewModel"}] An error occurred during execution
Spice86.Emulator.InterruptHandlers.UnhandledInterruptException: An error occurred while machine was in this state: Cycles=8077 CS:IP=0xF000:0x20/0xF0020 EAX=0x4B00 EBX=0x0 ECX=0x6 EDX=0x1A ESI=0x706 EDI=0x54 EBP=0x22B ESP=0x172 SS=0x1000 DS=0x1000 ES=0x1000 FS=0x0 GS=0x0 flags=0x2 (         ).
Error is: callbackNumber=0x21, operation=0x4B
   at Spice86.Emulator.Callback.IndexBasedDispatcher.GetCallback(Int32 index) in /home/akawolf/sources/Spice86/src/Spice86/Emulator/Callback/IndexBasedDispatcher.cs:line 27
   at Spice86.Emulator.Callback.IndexBasedDispatcher.Run(Int32 index) in /home/akawolf/sources/Spice86/src/Spice86/Emulator/Callback/IndexBasedDispatcher.cs:line 18
   at Spice86.Emulator.InterruptHandlers.Dos.DosInt21Handler.Run() in /home/akawolf/sources/Spice86/src/Spice86/Emulator/InterruptHandlers/Dos/DosInt21Handler.cs:line 363
   at Spice86.Emulator.Callback.IndexBasedDispatcher.Run(Int32 index) in /home/akawolf/sources/Spice86/src/Spice86/Emulator/Callback/IndexBasedDispatcher.cs:line 18
   at Spice86.Emulator.CPU.Cpu.Callback(UInt16 callbackIndex) in /home/akawolf/sources/Spice86/src/Spice86/Emulator/CPU/CPU.cs:line 203
   at Spice86.Emulator.CPU.Cpu.Grp4() in /home/akawolf/sources/Spice86/src/Spice86/Emulator/CPU/CPU.cs:line 1959
   at Spice86.Emulator.CPU.Cpu.ExecOpcode(Byte opcode) in /home/akawolf/sources/Spice86/src/Spice86/Emulator/CPU/CPU.cs:line 1557
   at Spice86.Emulator.CPU.Cpu.ExecuteNextInstruction() in /home/akawolf/sources/Spice86/src/Spice86/Emulator/CPU/CPU.cs:line 83
   at Spice86.Emulator.VM.Machine.RunLoop() in /home/akawolf/sources/Spice86/src/Spice86/Emulator/VM/Machine.cs:line 236
   at Spice86.Emulator.VM.Machine.Run() in /home/akawolf/sources/Spice86/src/Spice86/Emulator/VM/Machine.cs:line 212
   at Spice86.Emulator.ProgramExecutor.Run() in /home/akawolf/sources/Spice86/src/Spice86/Emulator/ProgramExecutor.cs:line 54
   at Spice86.UI.ViewModels.MainWindowViewModel.RunMachine() in /home/akawolf/sources/Spice86/src/Spice86/Ui/ViewModels/MainWindowViewModel.cs:line 219```
at latest master.

I guess it should run successfully?

**Comment by maximilien-noal** [comment]
It should work with DNCDPRG.EXE, not DUNE.EXE

```bash
Spice86 -e DNCDPRG.EXE
```

Besides DUNE.EXE is the loader which eventually launches DNCDPRG.EXE, it's not needed.

**Comment by akaWolf** [comment]
I see.
Still have a lot of errors and no image:
```
❯ Spice86 -e DNCDPRG.EXE
[13:01:54 WRN {SourceContext="Spice86.Emulator.InterruptHandlers.Dos.DosFileManager"}] FileNotFoundErrorWithLog: File dnmaj1 not found!
[13:01:54 ERR {SourceContext="Spice86.Emulator.InterruptHandlers.Dos.DosInt21Handler"}] DOS operation failed with an error. Int will return to 0x1000:0xF215/0x1F215. . State is Cycles=136 CS:IP=0xF000:0x20/0xF0020 EAX=0x3D00 EBX=0x0 ECX=0x1F4C EDX=0x3834 ESI=0x3800 EDI=0xDD2B EBP=0x81 ESP=0x3CBC SS=0x1F4C DS=0x1F4C ES=0x1F4C FS=0x0 GS=0x0 flags=0x46 (     Z P )
[13:01:54 WRN {SourceContext="Spice86.Emulator.InterruptHandlers.Dos.DosFileManager"}] FileNotFoundErrorWithLog: File dnmaj2 not found!
[13:01:54 ERR {SourceContext="Spice86.Emulator.InterruptHandlers.Dos.DosInt21Handler"}] DOS operation failed with an error. Int will return to 0x1000:0xF215/0x1F215. . State is Cycles=214 CS:IP=0xF000:0x20/0xF0020 EAX=0x3D00 EBX=0x0 ECX=0x1F4C EDX=0x3834 ESI=0x3800 EDI=0xDD2B EBP=0x81 ESP=0x3CBC SS=0x1F4C DS=0x1F4C ES=0x1F4C FS=0x0 GS=0x0 flags=0x46 (     Z P )
[13:01:54 WRN {SourceContext="Spice86.Emulator.InterruptHandlers.Dos.DosFileManager"}] FileNotFoundErrorWithLog: File dnmaj3 not found!
...
```

**Comment by maximilien-noal** [comment]
dnmaj files are not used, those errors are expected.

If you have dune.dat along side dncdprg.exe, you should eventually get an
image.

May I ask what OS are you using ?

Le dim. 17 avr. 2022 à 12:04, Artjom Vejsel ***@***.***> a
écrit :

**Comment by akaWolf** [comment]
Yes finally I got image.
Thanks.

I use GNU/Linux.

**Comment by maximilien-noal** [comment]
Cool, then I close this issue.

Thank you for your feedback !
